apiVersion: batch/v1
kind: Job
metadata:
  name: claims-management-app-job
spec:
  template:
    spec:
      volumes:
        - name: env-secret
          secret:
            secretName: qa-secret
      containers:
        - name: downloader
          volumeMounts:
            - name: env-secret
              mountPath: /etc/secret