resources:
  - job.yaml
#  - configmap.yaml

namePrefix: qa-
commonLabels:
  env: qa


configMapGenerator:
  - name: claims-management-app-cm
    literals:
    -  artifactName="bpmn-poc.tar.gz"
    -  artifactSha256="chaning claims in qa configmap-3"
    -  artifactUrl="abcd.efgh"
patches:
  - path: add-secret-volume.yaml