resources:
  - job.yaml
#  - configmap.yaml

namePrefix: dev-
commonLabels:
  env: dev


configMapGenerator:
  - name: claims-management-app-cm
    literals:
    -  artifactName="bpmn-poc.tar.gz"
    -  artifactSha256="chaning claims in dev configmap-3"
    -  artifactUrl="abcd.efgh"

patches:
  - path: add-secret-to-job.yaml
    target:
      kind: Job
      name: claims-management-app-job
